/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommentList: typeof import('./src/components/comment/CommentList.vue')['default']
    CommentOne: typeof import('./src/components/comment/CommentOne.vue')['default']
    DatePicker: typeof import('./src/components/date-picker/DatePicker.vue')['default']
    ListItem: typeof import('./src/components/date-picker/ListItem.vue')['default']
    PullRefresh: typeof import('./src/components/pull-refresh/PullRefresh.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollContainer: typeof import('./src/components/date-picker/ScrollContainer.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
  }
}
